name: Compilar con Gemix

on:
  push:
    paths:
      - 'examples/**/*.prg'
  pull_request:
    paths:
      - 'examples/**/*.prg'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-2.0-0 libsdl2-dev
      
      - name: Verificar estructura de directorios
        run: |
          echo "Verificando estructura de directorios..."
          ls -la
          ls -la bin/
          ls -la bin/modules/
          ls -la bin/modules/linux/
          ls -la bin/modules/linux/release/
      
      - name: Configurar permisos de ejecución
        run: |
          chmod +x bin/gemix
          chmod +x scripts/compilar_github.sh
          find bin -name "*.so*" -exec chmod +x {} \;
          find bin/modules -name "*.so" -exec chmod +x {} \;
      
      - name: Instalar dependencias específicas para SDL2
        run: |
          sudo apt-get install -y libsdl2-2.0-0 libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
      
      - name: Configurar librerías compartidas
        run: |
          echo "Configurando librerías compartidas..."
          
          # Crear directorio temporal para las librerías
          sudo mkdir -p /usr/local/lib/gemix
          
          # Copiar las librerías al directorio del sistema
          sudo cp bin/libSDL2-2.0.so.0 /usr/local/lib/gemix/
          sudo cp bin/libfmod.so.7 /usr/local/lib/gemix/
          sudo cp bin/libfmodex-4.44.61.so /usr/local/lib/gemix/
          sudo cp bin/libfmodstudio.so.7 /usr/local/lib/gemix/
          
          # Crear enlaces simbólicos
          sudo ln -sf /usr/local/lib/gemix/libSDL2-2.0.so.0 /usr/lib/libSDL2-2.0.so.0
          sudo ln -sf /usr/local/lib/gemix/libfmod.so.7 /usr/lib/libfmod.so.7
          sudo ln -sf /usr/local/lib/gemix/libfmodex-4.44.61.so /usr/lib/libfmodex-4.44.61.so
          sudo ln -sf /usr/local/lib/gemix/libfmodstudio.so.7 /usr/lib/libfmodstudio.so.7
          
          # Configurar ruta de librerías compartidas
          echo "/usr/local/lib/gemix" | sudo tee /etc/ld.so.conf.d/gemix.conf
          
          # Actualizar cache de librerías compartidas
          sudo ldconfig
          
          # Configurar LD_LIBRARY_PATH
          export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/bin:/usr/local/lib/gemix:$LD_LIBRARY_PATH
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> $GITHUB_ENV
      
      - name: Compilar ejemplos usando script especializado
        run: |
          for file in examples/**/*.prg; do
            ./scripts/compilar_github.sh "$file" || true
            echo ""
          done
          
      - name: Listar archivos generados
        run: |
          echo "Archivos generados:"
          find examples -type f -not -name "*.prg" -not -name "*.md" || true